# Generated by Django 3.2.8 on 2021-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipodocumento', models.CharField(max_length=5)),
                ('documento', models.CharField(max_length=40)),
                ('lu_residencia', models.CharField(max_length=50)),
                ('fecha_na', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=80)),
                ('telefono', models.BigIntegerField()),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
